export enum LeagueStageFormat {
  ROUND_ROBIN_BO1 = 'ROUND_ROBIN_BO1',
  ROUND_ROBIN_BO3 = 'ROUND_ROBIN_BO3',
  DOUBLE_ELIMINATION_BO1 = 'DOUBLE_ELIMINATION_BO1',
  DOUBLE_ELIMINATION_BO3 = 'DOUBLE_ELIMINATION_BO3',
  DOUBLE_ELIMINATION_BO5 = 'DOUBLE_ELIMINATION_BO5',
}
